## Configure G4SBS for gmn (Q^2 = 13.5 GeV^2)
/g4sbs/filename        cosmics_gmn.root   ## Output rootfile

## Configure Experiment
/g4sbs/exp             gmn

## Configure the target
/g4sbs/target          LD2
/g4sbs/targlen        15.0 cm           ## Target Length

## Configure generator settings
#/g4sbs/kine           gun           ## Generator
/g4sbs/kine           cosmics           ## Generator
/g4sbs/shootgeantino  true           ## Generator
/g4sbs/eemin          100.0 GeV
/g4sbs/eemax          100.0 GeV
/g4sbs/cosmicpointer  -4.703 -3.048 +16.960 m
/g4sbs/cosmicpointerradius 1.2 m
/g4sbs/cosmicmaxangle 90.0 deg


## Configure standard detector settings
/g4sbs/hcaldist        17.0 m
/g4sbs/hcalvoffset     45.00 cm
/g4sbs/beamlineconfig  4
/g4sbs/sbsclampopt     3                 ## Disable all field clamps

## Configure the magnets
/g4sbs/bbfield         1
#/g4sbs/48d48field      1
/g4sbs/tosfield        GMN13_field.table
#/g4sbs/invertfield      true #for use with "Moeller" charged geantino
/g4sbs/bbang           33.0 deg
/g4sbs/bbdist          1.55 m
/g4sbs/sbsang          14.9 deg
/g4sbs/48D48dist       3.1 m
/g4sbs/sbsmagfield     0.97 tesla

/g4sbs/buildSBSsieve true
/g4sbs/buildBBsieve true

/g4sbs/uselead 1
/g4sbs/bbshieldconfig 4

# Use this open statement to create an OpenGL view:
#/vis/open OGLSX 1500x900-0+0
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume worlds
#
#
#/vis/geometry/set/colour bbyokewgapLog -1 0 1 0 1
#/vis/geometry/set/forceWireframe entwin_log -1 1
#
# Set specific colour for identification : ghost parallel geometry envelope ("ghost") as yellow
#
# Specify view angle:
#/vis/viewer/set/lightsThetaPhi  155.0 0 deg
/vis/viewer/set/viewpointThetaPhi -90 -89.5 deg
/vis/viewer/set/viewpointThetaPhi  90.0 0 deg
#/vis/viewer/set/targetPoint -3.3945 0.0 +12.756 m
#/vis/viewer/set/viewpointThetaPhi 165.1 0 deg
#
# Specify zoom value:
/vis/viewer/zoom 1.0
#
# Specify style (surface or wireframe):
/vis/viewer/set/style surface
#
# Draw coordinate axes:
/vis/scene/add/axes -4.703 +33.0 +16.960 1.0 m
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
/vis/scene/add/hits
#
# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#/vis/filtering/trajectories/particleFilter-0/add neutron
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set e+ red
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton white
/vis/modeling/trajectories/drawByParticleID-0/setRGBA proton 1.0 0.0 1.0 1.0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA neutron 1.0 1.0 0.0 1.0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA pi- 1. 0.2 1.0 1.0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA kaon+ 0.3 1.0 0.5 1.0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA kaon- 0.3 1.0 0.5 1.0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA mu- 0.25 0.75 0.5 1.0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA geantino 0.2 0.65 0.5 1.0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA chargedgeantino 1.0 0.65 0.5 1.0
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate 10000
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
/g4sbs/run  100000
#/vis/geometry/set/visibility RICHbox_log -1 0
#/vis/geometry/set/visibility harm_mother_log -1 0
/vis/viewer/flush
#/vis/viewer/set/viewpointThetaPhi 15.0 0.0 deg
#/vis/viewer/flush
#/vis/viewer/set/viewpointThetaPhi 20.0 0.0 deg
#/vis/viewer/zoom 2
#/vis/viewer/flush
