## Configure G4SBS for TDIS
##/g4sbs/filename        tdis_h2_elastic_1.5T.root   ## Output rootfile

## Configure Experiment
/g4sbs/exp             tdis

## Configure the target
/g4sbs/target          H2
/g4sbs/targlen         40.0 cm           ## Target Length
/g4sbs/targdiam        1.0 cm          ## Target Diameter
/g4sbs/tdistgtwallthick 0.02 mm


/g4sbs/kine            wiser
/g4sbs/hadron          pi-


/g4sbs/beamE	       11.0 GeV

# pion energy range 
/g4sbs/hthmin           5.0 deg
/g4sbs/hthmax          25.0 deg
/g4sbs/hphmin         120.0 deg
/g4sbs/hphmax         240.0 deg
/g4sbs/ehmin           0.5 GeV
/g4sbs/ehmax          10.0 GeV

## Configure standard detector settings
/g4sbs/hcaldist        7.0 m
/g4sbs/hcalvoffset     0.75 m
/g4sbs/hcalhoffset    -0.25 m
/g4sbs/hcalpsconfig    2
/g4sbs/hcalpsvoffset     0.75 m
/g4sbs/hcalpshoffset     0.00 m

/g4sbs/sbstrkrdist     4.4 m
/g4sbs/sbstrkrpitch    5.0 deg

/g4sbs/richdist        5.0 m
/g4sbs/richgas         CF4
/g4sbs/userichaero     false

## Configure the magnets
/g4sbs/bbfield         0
/g4sbs/sbsmagfield    -0.90 tesla
/g4sbs/48d48field      1
/g4sbs/sbsang          12.0 deg
/g4sbs/48D48dist       2.5 m
/g4sbs/sbsclampopt     0                 ## Disable all field clamps

/g4sbs/solunifield	true
/g4sbs/solunimag	4.7
#/g4sbs/solunimag	1.5
#/g4sbs/soltoscafield	true
#/g4sbs/soltoscascale	1.0
#/g4sbs/soltoscaoffset	200.0 mm

/g4sbs/treeflag 1
/g4sbs/totalabs true

#/g4sbs/steplimit LACmod_log 1 
#/g4sbs/steplimit log_HCAL

/g4sbs/keepsdtrackinfo all true

## Run xxx events
##/g4sbs/run           10000
