# Example SIDIS script:
# To run with no optical photon production, do:
# ./g4sbs scripts/preinit_nockov_noscint.mac scripts/sidis_example_script.mac
# To run with Cerenkov ONLY:
# ./g4sbs scripts/preinit_ckov_noscint.mac scripts/sidis_example_script.mac
# To run with Scintillation ONLY:
# ./g4sbs scripts/preinit_nockov_scint.mac scripts/sidis_example_scripts.mac
# To run with both Cerenkov and Scintillation ON, do:
# ./g4sbs scripts/preinit_ckov_scint.mac scripts/sidis_example_scripts.mac
/g4sbs/filename sidis_example.root
/g4sbs/beamcur  60.0 muA
/g4sbs/target          H2
/g4sbs/targpres        10 atmosphere     ## Target pressure
/g4sbs/targlen         60.0 cm           ## Target Length
/g4sbs/targgenhhconfig 982               ## Q2 = 9.82 GeV^2 
/g4sbs/targgenDRX      0 deg             ## target angular misalignment about x axis  
/g4sbs/targgenDRY      0 deg             ## target angular misalignment about y axis
/g4sbs/targgenDRZ      0 deg             ## target angular misalignment about z axis
/g4sbs/targgenColEnable true
/g4sbs/usehadronfilter true


/g4sbs/rasterx  2.0 mm
/g4sbs/rastery  2.0 mm
/g4sbs/exp      sidis
/g4sbs/hadron   pi+
/g4sbs/kine     sidis
#/g4sbs/kine beam

/g4sbs/runtime     1.0 s
/g4sbs/beamE      11.0 GeV
/g4sbs/bbang      30.0 deg
/g4sbs/bbdist      1.55 m
/g4sbs/sbsang    14.0 deg
/g4sbs/hcaldist    8.5 m
/g4sbs/hcalhoffset -30.0 cm
/g4sbs/48D48dist   2.8 m
/g4sbs/sbsmagfield  1.4 tesla
/g4sbs/48d48field   1
/g4sbs/bbfield      1
/g4sbs/sbsclampopt  2
/g4sbs/uselead 0
/g4sbs/richdist    4.6 m
/g4sbs/richhoffset 0.025 m
/g4sbs/sbstrkrdist 5.925 m
/g4sbs/sbstrkrpitch 0.0 deg
/g4sbs/userichaero true
/g4sbs/richgas     C4F10
/g4sbs/grinchgas   C4F10
/g4sbs/thmin      24.0 deg
/g4sbs/thmax      39.0 deg
/g4sbs/phmin     -35.0 deg
/g4sbs/phmax      35.0 deg
#/g4sbs/phmin     150.0 deg
#/g4sbs/phmax     220.0 deg
/g4sbs/hthmin     10.0 deg
/g4sbs/hthmax    20.0 deg
/g4sbs/hphmin    140.0 deg
/g4sbs/hphmax    220.0 deg
/g4sbs/eemin      0.5 GeV
/g4sbs/eemax      6.0 GeV
/g4sbs/ehmin      1.0 GeV
/g4sbs/ehmax      10.5 GeV

/g4sbs/treeflag 1

/g4sbs/totalabs true
/g4sbs/rejectionsampling false
/g4sbs/keepsdtrackinfo all true

#new commands for polarized target SIDIS:
/g4sbs/targpolmag 0.55
/g4sbs/targpoldirection 0 1 0
# turn on randomization of target spin direction
/g4sbs/randomizetargetspin 1
# specify number of discrete target spin states to simulate:
/g4sbs/numtargspinstates 4
# specify target spin polar angles:
/g4sbs/targthetaspin 90 90 90 90 deg
# specify target spin azimuthal angles:
/g4sbs/targphispin 0 90 180 270 deg

/g4sbs/eventstatusevery 100
#/g4sbs/run 10000


# Use this open statement to create an OpenGL view:
/vis/open OGLI 800x800-0+0
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume worlds
#
# Set specific colour for identification : ghost parallel geometry envelope ("ghost") as yellow
#
# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 90 91 deg
# Help speed up visualization with linesegmentsperciricle:
/vis/viewer/set/lineSegmentsPerCircle 24 
#
# Specify zoom value:
/vis/viewer/zoom 2.5
#
# Specify style (surface or wireframe):
/vis/viewer/set/style surface
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 1 m
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
/vis/scene/add/hits
#
# To draw only gammas:
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/add neutron
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton white
/vis/modeling/trajectories/drawByParticleID-0/setRGBA pi- 1. 0.2 1.0 1.0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA kaon+ 0.3 1.0 0.5 1.0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA kaon- 0.3 1.0 0.5 1.0
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate 10000
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
/g4sbs/run  1
#/vis/geometry/set/visibility RICHbox_log -1 0
/vis/viewer/flush
