## Configure G4SBS for genrp (Q^2 = 4.5 GeV^2)
/g4sbs/filename        WAPP_test.root	   ## Output rootfile

## Configure Experiment
/g4sbs/exp             gmn

## Configure the target
/g4sbs/target          LD2
/g4sbs/targlen         15.0 cm           ## Target Length
 
## Configure generator settings
/g4sbs/kine            wapp           ## Generator
#/g4sbs/kine 		beam
#/g4sbs/pythia6file     Pythia_E6p6GeV_neutron.root
#/g4sbs/hadron 	       pi0
/g4sbs/beamcur         5 muA
/g4sbs/beamE           6.6 GeV
/g4sbs/thmin           37.0 deg
/g4sbs/thmax           49.0 deg
/g4sbs/phmin           -30 deg
/g4sbs/phmax           30 deg
/g4sbs/hthmin           37.0 deg
/g4sbs/hthmax           49.0 deg
/g4sbs/hphmin           -30 deg
/g4sbs/hphmax           30 deg
/g4sbs/rasterx	       2.0 mm
/g4sbs/rastery 	       2.0 mm
/g4sbs/eemin 	       4.0 GeV
/g4sbs/eemax	       6.6 GeV
#/g4sbs/ehmin 	       0.2 GeV
#/g4sbs/ehmax 	       4.0 GeV
/g4sbs/tmin 	       3.5
/g4sbs/tmax 	       9.0
/g4sbs/userad	       0
/g4sbs/radthick        0.06
/g4sbs/radz 	       10.0 cm
# generation limits for pythia only:
#/g4sbs/thmin        0.0 deg
#/g4sbs/thmax	    180.0 deg
#/g4sbs/phmin	    -180.0 deg
#/g4sbs/phmax 	    180.0 deg
#/g4sbs/hthmin        0.0 deg
#/g4sbs/hthmax	    180.0 deg
#/g4sbs/hphmin	    -180.0 deg
#/g4sbs/hphmax 	    180.0 deg
#/g4sbs/eemin 	    0.0 GeV
#/g4sbs/eemax 	    6.6 GeV
#/g4sbs/ehmin 	    0.0 GeV
#/g4sbs/ehmax 	    6.6 GeV

## Configure standard detector settings
/g4sbs/hcaldist        8.5 m
/g4sbs/hcalvoffset     0.75 m
/g4sbs/sbsclampopt     2                 ## Front and rear field clamps

## Configure GEn-RP analyzer
/g4sbs/genrpAnalyzer 3

## Configure the magnets
/g4sbs/bbfield         1
/g4sbs/sbsmagfield     1.3 tesla # for + polarity (proton upbending)
#/g4sbs/sbsmagfield    -1.4 tesla # for - polarity (proton downbending)
/g4sbs/48d48field      1
/g4sbs/bbang           31.5 deg
/g4sbs/bbdist          1.55 m
/g4sbs/sbsang          31.5 deg
/g4sbs/48D48dist       2.25 m
# Unless and until I get some documentation of the coordinate system for this field map, we will NOT be using:
#/g4sbs/tosfield 	GEN-RP-tosca_newheader.table

/g4sbs/keepsdtrackinfo 	all true
/g4sbs/totalabs 	true
/g4sbs/cdetready 	false

## Run 100 events
/g4sbs/eventstatusevery		100
#/g4sbs/run             10000


#visualization stuff:
# Use this open statement to create an OpenGL view:
/vis/open OGLI 800x800-0+0
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors

/vis/viewer/set/background 1 1 1 0

#
# Draw geometry:
/vis/drawVolume worlds
#
# Set specific colour for identification : ghost parallel geometry envelope ("ghost") as yellow
#
# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 90 120 deg
#
# Specify zoom value:
/vis/viewer/zoom 2.2
#
# Specify style (surface or wireframe):
/vis/viewer/set/style surface
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 1 m
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
/vis/scene/add/hits
#
# To draw only gammas:
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add gamma
#/vis/filtering/trajectories/particleFilter-0/add neutron
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton green
/vis/modeling/trajectories/drawByParticleID-0/setRGBA proton  1.0 0 0 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA neutron 1 1 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA pi- 1. 0.2 1.0 1.0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA pi+ 1. 0.2 1.0 1.0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA kaon+ 0.3 1.0 0.5 1.0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA kaon- 0.3 1.0 0.5 1.0
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate 10000
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
/g4sbs/run  0
#/vis/geometry/set/visibility RICHbox_log -1 0
/vis/viewer/flush
