#/control/execute scripts/sidis_template.mac
/control/execute scripts/gep_12GeV2_template.mac
/g4sbs/kine pythia6
/g4sbs/pythia6file pythia11gev_job1.root
#/g4sbs/kine elastic
/g4sbs/uselead 1
# start with wide-open cuts:
/g4sbs/thmin 0 deg
/g4sbs/thmax 180 deg
/g4sbs/phmin -180 deg
/g4sbs/phmax 180 deg
/g4sbs/eemin 0. GeV
/g4sbs/eemax 15. GeV
#/g4sbs/keephistory Harm/FT true
#/g4sbs/keephistory Harm/FPP1 1
#/g4sbs/keephistory Harm/FPP2 0
#/g4sbs/keephistory Earm/ECAL false

# Use this open statement to create an OpenGL view:
/vis/open OGLIQt 800x800-0+0
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume worlds
#
# Set specific colour for identification : ghost parallel geometry envelope ("ghost") as yellow
#
# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 90 180 deg
#
# Specify zoom value:
/vis/viewer/zoom 2.5
#
# Specify style (surface or wireframe):
/vis/viewer/set/style surface
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 1 m
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
/vis/scene/add/hits
#
# To draw only gammas:
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/add neutron
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton white
/vis/modeling/trajectories/drawByParticleID-0/setRGBA pi- 1. 0.2 1.0 1.0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA kaon+ 0.3 1.0 0.5 1.0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA kaon- 0.3 1.0 0.5 1.0
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate 10000
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
/g4sbs/run  0

#/vis/geometry/set/visibility RICHbox_log -1 0
/vis/geometry/set/visibility lHCalo -1 0
/vis/geometry/set/visibility earm_mother_log -1 0
/vis/geometry/set/forceWireframe bigcoil_log -1 1
/vis/geometry/set/forceWireframe woundcoil_log -1 1
/vis/geometry/set/forceWireframe bigcoilthr_log -1 1
/vis/geometry/set/forceWireframe b48d48Log -1 1
/vis/geometry/set/forceWireframe leftslabLog -1 1
/vis/geometry/set/forceWireframe rightslabLog -1 1
/vis/geometry/set/forceWireframe FrontClamp_log -1 1
/vis/geometry/set/forceWireframe RearClamp_log -1 1
/vis/viewer/flush
