## Configure G4SBS for gen (Q^2 = 10 GeV^2)
/g4sbs/filename        gen_10GeV2.root   ## Output rootfile

## Configure Experiment
/g4sbs/exp             gen

## Configure the target
/g4sbs/target          3He
/g4sbs/targpres        10 atmosphere     ## Target pressure
/g4sbs/targlen         55.0 cm           ## Target Length
/g4sbs/targgenhhconfig 1018              ## Q2 = 10.18 GeV^2 

## Configure generator settings
/g4sbs/kine            elastic           ## Generator
/g4sbs/runtime         1.0 s
/g4sbs/beamcur         60.0 muA
/g4sbs/rasterx         4.0 mm
/g4sbs/rastery         4.0 mm
/g4sbs/beamoffsetx     0.0 mm 
/g4sbs/beamoffsety     0.0 mm
/g4sbs/beamE           8.8 GeV
/g4sbs/thmin           24.0 deg
/g4sbs/thmax           44.0 deg
/g4sbs/phmin           -50.0 deg
/g4sbs/phmax           50.0 deg

## Configure standard detector settings
/g4sbs/gemres          0.070 mm
# The following are commented out because they are obsolete:
# The BigBite detector package layout is finalized/standardized now
#/g4sbs/cerdist         0.57 m
#/g4sbs/gemsep          1.34 m
#/g4sbs/bbcaldist       1.4 m
#/g4sbs/gemconfig       1                 ## (Used to be 2, but changed to 1 on the recommendation of documentation on wiki)
/g4sbs/hcaldist        17.0 m
/g4sbs/hcalvoffset     0.0 m

## Configure the magnets
/g4sbs/bbfield         1
/g4sbs/sbsmagfield 1.4 tesla
/g4sbs/48d48field      1
/g4sbs/bbang           34.0 deg
/g4sbs/bbdist          1.55 m
/g4sbs/sbsang          17.5 deg
/g4sbs/48D48dist       2.8 m 
/g4sbs/uselead	       0

## Optional detectors 
/g4sbs/beamDiffuserEnable false

## Run 100 events
#/g4sbs/run             100


## Optional detectors 
/g4sbs/beamDiffuserEnable true 

/g4sbs/totalabs true

# /g4sbs/buildBBsieve 1

## Run 100 events
#/g4sbs/run             100

#visualization stuff:
# Use this open statement to create an OpenGL view:
/vis/open OGLI 800x800-0+0
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume worlds
#
# Set specific colour for identification : ghost parallel geometry envelope ("ghost") as yellow
#
# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 90 180 deg
#
# Specify zoom value:
# /vis/viewer/zoom 2.5
#
# Specify style (surface or wireframe):
/vis/viewer/set/style surface
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 1 m
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
# /vis/scene/add/hits
#
# To draw only gammas:
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add gamma
#/vis/filtering/trajectories/particleFilter-0/add neutron
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton white
/vis/modeling/trajectories/drawByParticleID-0/setRGBA pi- 1. 0.2 1.0 1.0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA kaon+ 0.3 1.0 0.5 1.0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA kaon- 0.3 1.0 0.5 1.0
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate 1 
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
/g4sbs/run  1
#/vis/geometry/set/visibility RICHbox_log -1 0

/vis/geometry/set/forceWireframe b48d48Log -1 1
/vis/geometry/set/forceWireframe FrontClamp_log -1 1

# /vis/viewer/flush
