#/bin/perl
$prefix=DDVCS;
$classname = $ARGV[0];
$dvcsn=$prefix.$classname;
print $dvcsn;
open(INC_FILE,"> $prefix$classname.hh\n");
print INC_FILE "#ifndef _$dvcsn\_\n";
print INC_FILE "#define _$dvcsn\_\n";
print INC_FILE "#include \"G4SBS$classname.hh\"\n";
print INC_FILE "\n";
print INC_FILE "class $dvcsn : public G4SBS$classname\n";
print INC_FILE "{\n";
print INC_FILE "$dvcsn();\n";
print INC_FILE "\~$dvcsn();\n";
print INC_FILE "};\n";
print INC_FILE "#endif\n";
close INC_FILE;

open(SRC_FILE,"> ../../src/ddvcs/$prefix$classname.cc\n");
print SRC_FILE "#include \"$dvcsn.hh\"\n";
print SRC_FILE "\n";
print SRC_FILE "$dvcsn\:\:$dvcsn()\n";
print SRC_FILE "{\n";
print SRC_FILE "}\n";
print SRC_FILE "\n";
print SRC_FILE "$dvcsn\:\:\~$dvcsn()\n";
print SRC_FILE "{\n";
print SRC_FILE "}\n";
print SRC_FILE "\n";
close SRC_FILE;
